### ISSUE TITLE
create file div

### ISSUE THREAD

**Issue by hai-ko** [hai-ko/viblex#10]
- [x] Icon 
- [x] Title
- [x] Source
- [x] Sol version
- [x] Path
- [x] Window size change bug
- [x] Camera zoom in on select
- [x] Window size change bug after max File View
- [x] State machine for view

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
weswinder, @jgkiano, @cao7113, @benhalverson, @Leask, @paulantoine2, @michaelmccallam, @HydraJedi, @nwhitmont, @enoch-su, @iesta, @HighTide2020, @dnovaes, @keepfocusontechnology, @head77x, @zeque98, @eveagle, @yiyawu, @pengyuanzhi, @YYvanYang, @CraigMcAulay1101, @yanisurbis, @evdatsion, @yinhangfeng, @Ahmzyjazzy, @developerdavi, @orbxball, @maxisgrom, @mcadamm4, @Guihgo, @yyxx2z, @gamunax, @schmty, @renyushu, @MJL85, @tasvln, @fmpaychain, @daikikohara, @akelstrom, @nadongjun, @lynamick6, @wuwe1, @pengjinning, @syrakozz, @jillmnolan, @rajpatel507, @zsrl, @1456118242, @isaac-infotrend, @rainstormza
